//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCup.Textures.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCup.Textures.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        internal static string btnSelectImage {
            get {
                return ResourceManager.GetString("btnSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string ConfirmBox {
            get {
                return ResourceManager.GetString("ConfirmBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string gbGender {
            get {
                return ResourceManager.GetString("gbGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string gbLanguage {
            get {
                return ResourceManager.GetString("gbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to apply?.
        /// </summary>
        internal static string lbAreYouSureYouWantApply {
            get {
                return ResourceManager.GetString("lbAreYouSureYouWantApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Players.
        /// </summary>
        internal static string lbFavoritePlayers {
            get {
                return ResourceManager.GetString("lbFavoritePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Team: .
        /// </summary>
        internal static string lbFavoriteTeam {
            get {
                return ResourceManager.GetString("lbFavoriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Ranking (visitors).
        /// </summary>
        internal static string lbMatchRanking {
            get {
                return ResourceManager.GetString("lbMatchRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Ranking.
        /// </summary>
        internal static string lbPlayerRanking {
            get {
                return ResourceManager.GetString("lbPlayerRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string lbPlayers {
            get {
                return ResourceManager.GetString("lbPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        internal static string men {
            get {
                return ResourceManager.GetString("men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Form.
        /// </summary>
        internal static string SettingsForm {
            get {
                return ResourceManager.GetString("SettingsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Form.
        /// </summary>
        internal static string StartForm {
            get {
                return ResourceManager.GetString("StartForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal scored.
        /// </summary>
        internal static string tabGoalScore {
            get {
                return ResourceManager.GetString("tabGoalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string tabPlayers {
            get {
                return ResourceManager.GetString("tabPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        internal static string tabRanking {
            get {
                return ResourceManager.GetString("tabRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        internal static string tabYellowCards {
            get {
                return ResourceManager.GetString("tabYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite it.
        /// </summary>
        internal static string tsmiFavoriteIt {
            get {
                return ResourceManager.GetString("tsmiFavoriteIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavorite it.
        /// </summary>
        internal static string tsmiRemoveFromFavorite {
            get {
                return ResourceManager.GetString("tsmiRemoveFromFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        internal static string women {
            get {
                return ResourceManager.GetString("women", resourceCulture);
            }
        }
    }
}
